import React,{useEffect,useMemo,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import{Canvas,useFrame,useThree}from"@react-three/fiber";
import{Text}from"@react-three/drei";
import{GLTFLoader}from"three/examples/jsm/loaders/GLTFLoader.js";
import*as THREE from"three";
import{A,url}from"./assets";
import"./style.css";

function Model({src,position=[0,0,0],rotation=[0,0,0],scale=1}){const r=useRef();useEffect(()=>{let live=true;new GLTFLoader().load(url(src),g=>{if(!live||!r.current)return;g.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});r.current.clear();r.current.add(g.scene)},undefined,()=>{});return()=>{live=false}},[src]);return <group ref={r}position={position}rotation={rotation}scale={scale}/>}

function Player({input,out}){const r=useRef(),v=useRef(new THREE.Vector3());useEffect(()=>{out.current=r.current},[out]);useFrame((_,dt)=>{if(!r.current)return;let x=input.current.x,z=input.current.z;if(x||z){let n=new THREE.Vector3(x,0,z).normalize(),speed=input.current.run?8:4.8;v.current.lerp(n.multiplyScalar(speed),1-Math.pow(.00001,dt));r.current.rotation.y=Math.atan2(v.current.x,v.current.z)}else v.current.lerp(new THREE.Vector3(),1-Math.pow(.0005,dt));r.current.position.addScaledVector(v.current,dt);r.current.position.x=THREE.MathUtils.clamp(r.current.position.x,-38,38);r.current.position.z=THREE.MathUtils.clamp(r.current.position.z,-38,38)});return <group ref={r}position={[0,0,12]}><Model src={A.people[0]}scale={1.75}/><Text position={[0,2.9,0]}fontSize={.2}color="white"anchorX="center">YOU</Text></group>}

function Camera({player}){const{camera}=useThree(),look=useMemo(()=>new THREE.Vector3(),[]);useFrame((_,dt)=>{const p=player.current?.position||new THREE.Vector3(0,0,12);camera.position.lerp(new THREE.Vector3(p.x,p.y+5.8,p.z+8.5),1-Math.pow(.0008,dt));look.set(p.x,p.y+1.2,p.z);camera.lookAt(look)});return null}

function Roads(){let a=[];for(let i=-3;i<=3;i++){a.push(<Model key={"v"+i}src={A.road}position={[i*12,0,0]}rotation={[0,Math.PI/2,0]}scale={2.2}/>);a.push(<Model key={"h"+i}src={A.road}position={[0,0,i*12]}scale={2.2}/>)}return <>{a}<Model src={A.roadCross}position={[0,0,0]}scale={2.2}/></>}

function MovingNPC({src,start,index}){const r=useRef(),phase=useMemo(()=>index*.9,[]);useFrame(({clock})=>{if(!r.current)return;const t=clock.elapsedTime*.42+phase;const radius=5+(index%3)*2;r.current.position.x=start[0]+Math.sin(t)*radius;r.current.position.z=start[1]+Math.cos(t*.8)*radius*.7;r.current.rotation.y=Math.atan2(Math.cos(t)*radius,-Math.sin(t)*radius)});return <group ref={r}position={[start[0],0,start[1]]}><Model src={src}scale={1.7}/></group>}

function TrafficCar({src,lane,index}){const r=useRef(),speed=2.5+index*.35;useFrame((_,dt)=>{if(!r.current)return;r.current.position.z+=speed*dt;if(r.current.position.z>42)r.current.position.z=-42});return <group ref={r}position={[lane,.2,-42]}rotation={[0,Math.PI,0]}><Model src={src}scale={1.5}/></group>}

function Town(){let b=[],h=[],t=[];[[-30,-30],[-18,-30],[18,-30],[30,-30],[-30,30],[-18,30],[18,30],[30,30],[-30,-18],[30,-18],[-30,18],[30,18]].forEach(([x,z],i)=>b.push(<Model key={"b"+i}src={A.buildings[i%A.buildings.length]}position={[x,0,z]}rotation={[0,i%2?Math.PI:0]}scale={2.8}/>));[[-25,-10],[-25,10],[25,-10],[25,10],[-10,-25],[10,-25],[-10,25],[10,25]].forEach(([x,z],i)=>h.push(<Model key={"h"+i}src={A.homes[i%A.homes.length]}position={[x,0,z]}scale={2.4}/>));[[-35,-8],[-35,8],[35,-8],[35,8],[-8,-35],[8,-35],[-8,35],[8,35]].forEach(([x,z],i)=>t.push(<Model key={"t"+i}src={A.trees[i%2]}position={[x,0,z]}scale={2.5}/>));return <><Roads/>{b}{h}{t}{[[-6,0],[6,0],[-12,0],[12,0]].map((p,i)=><TrafficCar key={"car"+i}src={A.cars[i%A.cars.length]}lane={p[0]}index={i}/>)}{[[-6,3],[5,4],[-3,-4],[4,-3],[0,7],[-8,-8],[8,8]].map((p,i)=><MovingNPC key={"n"+i}src={A.people[(i+1)%A.people.length]}start={p}index={i}/>)}{[[-12,-12,"LUCKY SHOP"],[12,-12,"DARTS BAR"],[-12,12,"POOL HOUSE"],[12,12,"ARCADE"]].map((x,i)=><Text key={i}position={[x[0],4,x[1]]}fontSize={.38}color="white"anchorX="center">{x[2]}</Text>)}</>}

function App(){const input=useRef({x:0,z:0,run:false}),player=useRef(),[speed,setSpeed]=useState("WALK"),[joy,setJoy]=useState(false);useEffect(()=>{const down=e=>{const k=e.key.toLowerCase();if(k==="w"||k==="arrowup")input.current.z=-1;if(k==="s"||k==="arrowdown")input.current.z=1;if(k==="a"||k==="arrowleft")input.current.x=-1;if(k==="d"||k==="arrowright")input.current.x=1;if(k==="shift"){input.current.run=true;setSpeed("RUN")}};const up=e=>{const k=e.key.toLowerCase();if(k==="w"||k==="s"||k==="arrowup"||k==="arrowdown")input.current.z=0;if(k==="a"||k==="d"||k==="arrowleft"||k==="arrowright")input.current.x=0;if(k==="shift"){input.current.run=false;setSpeed("WALK")}};addEventListener("keydown",down);addEventListener("keyup",up);return()=>{removeEventListener("keydown",down);removeEventListener("keyup",up)}},[]);const move=e=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.touches?.[0]?.clientX||e.clientX)-r.left-r.width/2,z=(e.touches?.[0]?.clientY||e.clientY)-r.top-r.height/2;input.current.x=THREE.MathUtils.clamp(x/(r.width/2),-1,1);input.current.z=THREE.MathUtils.clamp(z/(r.height/2),-1,1)};const stop=()=>{input.current.x=0;input.current.z=0;setJoy(false)};return <div className="game"><Canvas shadows dpr={[1,1.5]}camera={{position:[0,6,20],fov:55}}><color attach="background"args={["#9eb8cf"]}/><ambientLight intensity={1.2}/><directionalLight castShadow position={[-20,28,15]}intensity={2.4}shadow-mapSize-width={2048}shadow-mapSize-height={2048}/><Town/><Player input={input}out={player}/><Camera player={player}/></Canvas><div className="hud"><div className="brand"><b>BET CITY</b><span>SMALL TOWN</span></div><div className="controls"><strong>{speed}</strong><span>WASD / ARROWS · SHIFT RUN</span></div><div className="status">LIVE FREE ROAM · NPCs + TRAFFIC MOVING</div></div><div className="joystick" onTouchStart={()=>setJoy(true)} onTouchMove={move} onTouchEnd={stop} onMouseDown={()=>setJoy(true)} onMouseMove={e=>{if(joy)move(e)}} onMouseUp={stop}><div className="stick" style={{transform:"translate("+(input.current.x*28)+"px,"+(input.current.z*28)+"px)"}}/></div></div>}createRoot(document.getElementById("root")).render(<App/>);